name: Deployment Parallel
on: push
jobs:
    lint:
        runs-on: Ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-Node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: linting code
              run: npm run lint
    test:
      needs: lint
      runs-on: Ubuntu-latest
      steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Setup Node
            uses: actions/setup-Node@v3
            with:
              node-version: 18
          - name: Install dependencies
            run: npm ci
          - name: testing code
            run: npm run test
    deploy:
      needs: test
      runs-on: Ubuntu-latest
      steps:
          - name: Checkout Code
            uses: actions/checkout@v3
          - name: Setup Node
            uses: actions/setup-Node@v3
            with:
              node-version: 18
          - name: Install dependencies
            run: npm ci
          - name: deploying code
            run: npm run build
          - name: Finishing the Job
            run: echo "Code Deployment Complete"